hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

app:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app_dashboard:
    path: /dashboard
    defaults: { _controller: AppBundle:Default:dashboard }

# api:
#     resource: "@ApiBundle/Resources/config/routing.yml"
#     prefix:   /api/
