security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login:
        #     pattern:  ^/api/login
        #     stateless: true
        #     anonymous: true
        #     form_login:
        #         check_path: /api/login_check
        #         success_handler:          lexik_jwt_authentication.handler.authentication_success
        #         failure_handler: lexik_jwt_authentication.handler.authentication_failure
        #         require_previous_session: false

        # api:
        #     pattern:   ^/api
        #     stateless: true
        #     guard:
        #         authenticators:
        #             - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            oauth:
                resource_owners:
                    facebook:         /login/check-facebook
                login_path:           /login
                use_forward:          false
                failure_path:         /login
                default_target_path:  /dashboard
                oauth_user_provider:
                    service: hafta.oauth_aware.user_provider
            # Turn on anonymous for testings need.
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
