imports:
    - { resource: "@ApiBundle/Resources/config/services.yml" }

parameters:

services:
   hafta.oauth_aware.user_provider:
       class: AppBundle\Security\HaftaFOSUBUserProvider
       arguments: ['@fos_user.user_manager', { facebook: facebookId }]
